version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - $PWD/.volumes/redis/dir:/data
  exporter:
    restart: unless-stopped
    depends_on:
      - redis
    build:
      context: .
    environment:
      HOST: "::"
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROM_PREFIX: bull
      BULL_PREFIX: bull
    ports:
      - 3000:3000
